default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: ticketee_development

 
test:
  <<: *default
  database: ticketee_test

production:
  <<: *default
  database: ticketee_production
  username: ticketee
  password: <%= ENV['TICKETEE_DATABASE_PASSWORD'] %>
